import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Arif",
      email: "arif@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Patrick",
      email: "patrick@example.com",
      password: bcrypt.hashSync("123", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt12",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "Slim shirt for man",
    },
    {
      name: "Adidas T-shirt2",
      category: "T-shirts",
      image: "/images/p2.jpg",
      price: 70,
      countInStock: 2,
      brand: "Adidas",
      rating: 2.5,
      numReviews: 102,
      description: "T-shirt for man",
    },
    {
      name: "Nike Slim Shirt2",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 130,
      brand: "Nike",
      rating: 1.5,
      numReviews: 10,
      description: "Slim shirt for man",
    },
    {
      name: "Nike Slim Shirt3",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 5,
      numReviews: 10,
      description: "Slim shirt for man",
    },
    {
      name: "Nike Slim Shirt4",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 120,
      countInStock: 130,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Slim shirt for man",
    },
    {
      name: "Nike Slim Shirt5",
      category: "Shirts",
      image: "/images/p6.jpg",
      price: 120,
      countInStock: 130,
      brand: "Nike",
      rating: 0.5,
      numReviews: 10,
      description: "Slim shirt for man",
    },
  ],
};

export default data;
