const data = {
  products: [
    {
      _id: 1,
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock:10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "Slim shirt for man",
    },
    {
      _id: 2,
      name: "Adidas T-shirt",
      category: "T-shirts",
      image: "/images/p2.jpg",
      price: 70,
      countInStock:2,
      brand: "Adidas",
      rating: 2.5,
      numReviews: 102,
      description: "T-shirt for man",
    },
    {
      _id: 3,
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStock:130,
      brand: "Nike",
      rating: 1.5,
      numReviews: 10,
      description: "Slim shirt for man",
    },
    {
      _id: 4,
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock : 0,
      brand: "Nike",
      rating: 5,
      numReviews: 10,
      description: "Slim shirt for man",
    },
    {
      _id: 5,
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 120,
      countInStock:130,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Slim shirt for man",
    },
    {
      _id: 6,
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p6.jpg",
      price: 120,
      countInStock:130,
      brand: "Nike",
      rating: 0.5,
      numReviews: 10,
      description: "Slim shirt for man",
    },
  ],
};

export default data;
